# File listing input reads, better setting this at command line with "--config input=XXX.csv"
# Should use absolute paths
input:

# TODO
# Optional tools to run
run_checkm: true
run_busco: true

# SPAdes parameters
kmers: "21,33,55"
min_scaffold_length: 1000 # for bbtools reformat

# BUSCO parameters
busco_version: 3
busco_database: /hpc-home/mcgowan/databases/busco3_datasets/eukaryota_odb9/
augustus_species:

# MetaBat2 parameters
metabat2_min_contig: 1500

# Tiara parameters
tiara_min_length: 1000

# EukRep parameters
eukrep_min_length: 1000

# Blobtools parameters
diamond_database: /hpc-home/mcgowan/DToL_Protists/data/results/CB-GENANNO-476_DToL_Protists/Reference/databases/diamond/reference_proteomes.dmnd
megablast_database: /ei/public/databases/blast/ncbi/nt_20200707/nt
nodesdb: /hpc-home/mcgowan/DToL_Protists/data/results/CB-GENANNO-476_DToL_Protists/Reference/databases/blobtools/nodesdb

# CAT parameters
cat_database: cat_database: /ei/projects/e/e5f1ee13-d3bf-4fec-8be8-38c6ad26aac3/data/results/CB-GENANNO-476_DToL_Protists/Reference/databases/CAT/CAT_prepare_20210107/2021-01-07_CAT_database
taxonomy_dir: /ei/projects/e/e5f1ee13-d3bf-4fec-8be8-38c6ad26aac3/data/results/CB-GENANNO-476_DToL_Protists/Reference/databases/CAT/CAT_prepare_20210107/2021-01-07_taxonomy
diamond_path: /ei/projects/e/e5f1ee13-d3bf-4fec-8be8-38c6ad26aac3/data/results/CB-GENANNO-476_DToL_Protists/Reference/databases/CAT/CAT_prepare_20210107/Diamond_2.0.6/diamond

# pr2 database
pr2_database: /hpc-home/mcgowan/databases/pr2/4.14.0/pr2_version_4.14.0_SSU_taxo_long.fasta