# File listing input reads, better setting this at command line with "--config input=XXX.csv"
# Should use absolute paths
input:

# Mode to run SPAdes in - "sc" for single-cell or "meta" for metagenome
assembly_type: sc

# Optional tools to run
run_checkm: true
run_busco: true

# SPAdes parameters
kmers: "21,33,55,77"
min_scaffold_length: 1000 # for bbtools reformat

# BUSCO parameters
busco_version: 3
busco_database: ....../databases/busco3_datasets/eukaryota_odb9/
augustus_species:

# MetaBat2 parameters
metabat2_min_contig: 1500

# Tiara parameters
tiara_min_length: 1000

# EukRep parameters
eukrep_min_length: 1000

# Blobtools parameters
diamond_database: ....../databases/diamond/reference_proteomes.dmnd
megablast_database: ....../databases/ncbi/nt_20220819/nt
nodesdb: ....../databases/blobtools/nodesdb
n_chunks: 6 # chunk the fasta file into N splits for the megablastn search; randomly to balance as input fasta will be sorted by sequence length

# CAT parameters
cat_database: ....../databases/CAT/20231120_CAT_nr/db
taxonomy_dir: ....../databases/CAT/20231120_CAT_nr/tax

# pr2 database
pr2_database: ....../databases/pr2/4.14.0/pr2_version_4.14.0_SSU_taxo_long.fasta

# cleanup options
cleanup_spades: true # deletes: corrected; K[0-9][0-9]; misc; tmp;
cleanup_cat: true # deletes: {SAMPLE}.CAT.alignment.diamond;
